// Selección curada de íconos Font Awesome (solid) para categorías —
// vocabulario típico de gobernanza / ITAM / seguridad, no el set completo
// de miles de íconos de FA.
export const CATEGORY_ICONS = [
  { value: 'tag', label: 'Etiqueta' },
  { value: 'shield-halved', label: 'Escudo' },
  { value: 'lock', label: 'Candado' },
  { value: 'key', label: 'Llave' },
  { value: 'eye', label: 'Visibilidad' },
  { value: 'triangle-exclamation', label: 'Alerta' },
  { value: 'circle-check', label: 'Cumplimiento' },
  { value: 'chart-line', label: 'Métrica' },
  { value: 'chart-pie', label: 'Reporte' },
  { value: 'server', label: 'Servidor' },
  { value: 'database', label: 'Base de datos' },
  { value: 'network-wired', label: 'Red' },
  { value: 'laptop', label: 'Equipo' },
  { value: 'mobile-screen', label: 'Móvil' },
  { value: 'cloud', label: 'Nube' },
  { value: 'wifi', label: 'Conectividad' },
  { value: 'gears', label: 'Proceso' },
  { value: 'clipboard-check', label: 'Auditoría' },
  { value: 'clipboard-list', label: 'Inventario' },
  { value: 'file-contract', label: 'Contrato' },
  { value: 'folder', label: 'Carpeta' },
  { value: 'dollar-sign', label: 'Costo' },
  { value: 'scale-balanced', label: 'Gobernanza' },
  { value: 'gavel', label: 'Política' },
  { value: 'book', label: 'Documentación' },
  { value: 'users', label: 'Personas' },
  { value: 'user-shield', label: 'Identidad' },
  { value: 'building', label: 'Organización' },
  { value: 'globe', label: 'Global' },
  { value: 'bug', label: 'Riesgo técnico' },
  { value: 'fire', label: 'Incidente' },
  { value: 'bolt', label: 'Disponibilidad' },
  { value: 'leaf', label: 'Sostenibilidad' },
  { value: 'flag', label: 'Prioridad' },
  { value: 'star', label: 'Destacado' },
  { value: 'bell', label: 'Notificación' },
  { value: 'lightbulb', label: 'Mejora' },
  { value: 'magnifying-glass', label: 'Descubrimiento' },
  { value: 'link', label: 'Relación' },
  { value: 'recycle', label: 'Ciclo de vida' },
];
